[target.aarch64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update && apt-get install --assume-yes libssl-dev:arm64"
]

[target.armv7-unknown-linux-musleabihf]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH"
]

[target.i686-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture i386",
    "apt-get update && apt-get install --assume-yes libssl-dev:i386"
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install --assume-yes libssl-dev"
]
